// Generated by LiveScript 1.4.0
(function(){
  var backbone, jsData, jsDataMongodb;
  backbone = require('backbone4000');
  jsData = require('js-data');
  jsDataMongodb = require('js-data-mongodb');
  exports.lego = backbone.Model.extend4000({
    after: 'logger',
    init: function(callback){
      var adapter;
      this.env.db = new jsData.DS();
      this.env.jsData = adapter = new this.settings.adapter(this.settings.options);
      this.env.db.registerAdapter('main', adapter, {
        'default': true
      });
      this.env.log("init db (" + colors.red(this.settings.name) + " at " + data + ")", {}, 'init', 'ok');
      return callback(undefined, data);
    }
  });
}).call(this);
