// Generated by LiveScript 1.4.0
(function(){
  var backbone, jsData;
  backbone = require('backbone4000');
  jsData = require('js-data');
  exports.lego = backbone.Model.extend4000({
    after: 'logger',
    init: function(callback){
      var adapter;
      this.env.db = new jsData.DS();
      this.env.jsData = adapter = new this.settings.adapter(this.settings.options);
      this.env.db.registerAdapter('main', adapter, {
        'default': true
      });
      this.env.log('jsdata initialized', {}, 'init', 'ok');
      return callback();
    }
  });
}).call(this);
